name: skillmodels
channels:
  - conda-forge
  - janosg
dependencies:
  - python=3.7
  - pip
  - conda-build
  - doc8
  - estimagic>=0.0.12
  - jupyter
  - matplotlib
  - mkl-service
  - nose
  - numba>=0.42
  - pandas>=0.24
  - pytest
  - pytest-mock
  - pytest-xdist
  - restructuredtext_lint
  - tox-conda
  - scipy>=1.2
  - seaborn
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - statsmodels>=0.9.0
  - anaconda-client
  - pip:
    - pre-commit
