name: skillmodels

channels:
  - defaults
  - conda-forge
  - janosg

dependencies:

  - python=3.7
  - numba>=0.42
  - statsmodels=0.9.0
  - seaborn=0.9.0
  - matplotlib=3.0.2
  - pandas>=0.24
  - pytest=5.1
  - pytest-mock
  - nose=1.3.7
  - pip=19.0.3
  - numpy
  - scipy=1.2
  - jupyter
  - mkl-service
  - estimagic>=0.0.12
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - pip:
    - doc8
    - pre-commit
    - pytest
    - pytest-mock
    - pytest-xdist
    - restructuredtext_lint
    - tox-conda
    - black


