name: skillmodels

channels:
  - defaults
  - conda-forge
  - janosg

dependencies:

  - python=3.7
  - numba>=0.42
  - statsmodels=0.9.0
  - seaborn
  - matplotlib
  - pandas>=0.24
  - pytest
  - pytest-mock
  - nose
  - pip
  - numpy
  - scipy=1.2
  - jupyter
  - mkl-service
  - estimagic>=0.0.12
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - pip:
    - doc8
    - pre-commit
    - pytest
    - pytest-mock
    - pytest-xdist
    - restructuredtext_lint
    - tox-conda
    - black


