name: skillmodels
channels:
  - conda-forge
  - opensourceeconomics
dependencies:
  - python=3.7
  - pip
  - conda-build
  - doc8
  - estimagic>=0.0.25
  - jupyter
  - matplotlib
  - mkl-service
  - nose
  - numba>=0.45
  - numpy<1.18
  - pandas>=0.24
  - click
  - pytest
  - pytest-mock
  - pytest-xdist
  - restructuredtext_lint
  - tox-conda
  - scipy
  - seaborn
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - statsmodels>=0.9
  - anaconda-client
  - nbsphinx
  - pdbpp
  - pip:
    - pre-commit
