name: skillmodels
channels:
  - conda-forge
  - opensourceeconomics
dependencies:
  - python=3.7
  - jax>=0.1.7
  - jaxlib>=0.1.51
  - pip
  - conda-build
  - doc8
  - jupyter
  - numpy
  - pandas>=0.24
  - pytest
  - pytest-xdist
  - restructuredtext_lint
  - tox-conda
  - scipy
  - seaborn
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3
  - anaconda-client
  - nbsphinx
  - pdbpp
  - filterpy
  - pip:
    - pre-commit
    - black
