package:
  name: skillmodels
  version: "0.0.0007"

source:
  path: ../skillmodels

requirements:
  build:
    - python
    - setuptools
  run:
    - python 3.5.2
    - numba 0.27.0
    - statsmodels 0.6.1
    - scipy 0.17.0
    - matplotlib 1.5.1
    - seaborn 0.7.0

test:
  files:
    - tests/fast_routines/numba_kalman_filters_test.py
    - tests/fast_routines/choldate_test.py
    - tests/fast_routines/qr_decomposition_test.py
    - tests/fast_routines/sigma_points_test.py
    - tests/fast_routines/sigma_points_from_filterpy.json
    - tests/fast_routines/numpy_kalman_filters_test.py
    - tests/model_functions/transition_functions_test.py
    - tests/pre_processing/model_spec_processor_test.py
    - tests/pre_processing/data_processor_test.py
    - tests/estimation/parse_params_test.py
    - tests/estimation/chs_model_test.py
  requires:
    - nose
    - numpy
    - numba

about:
  home: https://github.com/suri5471/skillmodels
  license: BSD
  license_file: LICENSE
  summary: Estimate non-linear skill formation models.
