package:
  name: skillmodels
  version: "0.0.0281"

source:
  path: ../skillmodels

requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.6
    - numba
    - statsmodels
    - scipy

test:
  files:
    - tests/fast_routines/kalman_filters_test.py
    - tests/fast_routines/choldate_test.py
    - tests/fast_routines/qr_decomposition_test.py
    - tests/fast_routines/sigma_points_test.py
    - tests/fast_routines/sigma_points_from_filterpy.json
    - tests/model_functions/transition_functions_test.py
    - tests/pre_processing/model_spec_processor_test.py
    - tests/pre_processing/data_processor_test.py
    - tests/estimation/parse_params_test.py
    - tests/estimation/skill_model_test.py
    - tests/estimation/wa_functions_test.py
    - tests/estimation/wa_test_with_no_squares_translog_model.py
    - tests/estimation/no_squares_translog_model.json
    - tests/fast_routines/transform_sigma_points_test.py
  requires:
    - nose
    - numpy
    - numba

about:
  home: https://github.com/suri5471/skillmodels
  license: BSD
  license_file: LICENSE
  summary: Estimate non-linear skill formation models.
