{% set data = load_setup_py_data() %}

package:
  name: skillmodels
  version: {{ data.get('version') }}

source:
  path: ../skillmodels

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - numba >=0.27
    - numpy
    - statsmodels >=0.6.1
    - scipy
    - seaborn
    - matplotlib

test:
  commands:
    - py.test
  files:
    - skillmodels/tests/fast_routines/kalman_filters_test.py
    - skillmodels/tests/fast_routines/choldate_test.py
    - skillmodels/tests/fast_routines/qr_decomposition_test.py
    - skillmodels/tests/fast_routines/sigma_points_test.py
    - skillmodels/tests/fast_routines/sigma_points_from_filterpy.json
    - skillmodels/tests/model_functions/transition_functions_test.py
    - skillmodels/tests/pre_processing/model_spec_processor_test.py
    - skillmodels/tests/pre_processing/data_processor_test.py
    - skillmodels/tests/estimation/parse_params_test.py
    - skillmodels/tests/estimation/skill_model_test.py
    - skillmodels/tests/estimation/wa_functions_test.py
    - skillmodels/tests/estimation/wa_with_no_squares_translog_model_test.py
    - skillmodels/tests/estimation/no_squares_translog_model.json
    - skillmodels/tests/fast_routines/transform_sigma_points_test.py
    - skillmodels/tests/estimation/likelihood_regression_test.py
    - skillmodels/tests/estimation/test_model2.json
    - skillmodels/tests/estimation/chs_test_ex2.dta
    - skillmodels/tests/estimation/regression_test_fixture.pickle
    - skillmodels/tests/fast_routines/generated_fixtures_update.json
  requires:
    - pytest
    - nose
    - pytest-mock


about:
  home: https://github.com/suri5471/skillmodels
  license: BSD
  license_file: LICENSE
  summary: Estimate non-linear skill formation models.
