{% set data = load_setup_py_data() %}

package:
  name: skillmodels
  version: {{ data.get('version') }}

source:
  path: ../skillmodels

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - numpy
    - pandas >=0.24
    - seaborn
    - scipy <=1.2.1
    - jax >= 0.1.7
    - jaxlib >= 0.1.51

test:
  commands:
    - py.test
  files:
    - skillmodels/tests/
  requires:
    - pytest
    - filterpy


about:
  home: https://github.com/suri5471/skillmodels
  license: BSD
  license_file: LICENSE
  summary: Estimate non-linear skill formation models.
