{% set data = load_setup_py_data() %}

package:
  name: skillmodels
  version: {{ data.get('version') }}

source:
  path: ../skillmodels

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - numba >=0.42
    - numpy
    - pandas >=0.24
    - statsmodels >=0.9.0
    - seaborn
    - matplotlib
    - estimagic >=0.0.25
    - scipy <=1.2.1

test:
  commands:
    - py.test
  files:
    - skillmodels/tests/
  requires:
    - pytest
    - nose
    - pytest-mock


about:
  home: https://github.com/suri5471/skillmodels
  license: BSD
  license_file: LICENSE
  summary: Estimate non-linear skill formation models.
