"""Functions to simulate a dataset generated by a latent factor model."""

import warnings
from typing import TYPE_CHECKING

import jax.numpy as jnp
import numpy as np
import pandas as pd
from jax import Array
from numpy.random import choice, multivariate_normal

from skillmodels.filtered_states import anchor_states_df

if TYPE_CHECKING:
    from collections.abc import Mapping

    from numpy.typing import NDArray

    from skillmodels.types import (
        Dimensions,
        EndogenousFactorsInfo,
        Labels,
        TransitionInfo,
    )
from skillmodels.kalman_filters import transform_sigma_points
from skillmodels.params_index import get_params_index
from skillmodels.parse_params import create_parsing_info, parse_params
from skillmodels.process_data import process_data
from skillmodels.process_debug_data import create_state_ranges
from skillmodels.process_model import process_model


def simulate_dataset(
    model_dict: dict,
    params: pd.DataFrame,
    n_obs: int | None = None,
    data: pd.DataFrame | None = None,
    policies: list[dict] | None = None,
) -> dict:
    """Simulate datasets generated by a latent factor model.

    Args:
        model_dict: The model specification. See: :ref:`model_specs`
        params: DataFrame with model parameters.
        n_obs: Number of simulated individuals
        data: Dataset in the same format as for estimation, containing
            information about observed factors and control variables.
        policies: list of dictionaries. Each dictionary specifies a
            a stochastic shock to a latent factor AT THE END of "period" for "factor"
            with mean "effect_size" and "standard deviation"

    Returns:
        observed_data: Dataset with measurements and control variables
            in long format

        latent_data: Dataset with latent factors in long format

    """
    if data is None and n_obs is None:
        raise ValueError("Either `data` or `n_obs` has to be provided.")

    model = process_model(model_dict)

    if model.labels.observed_factors and data is None:
        raise ValueError(
            "To simulate a model with observed factors, data cannot be None.",
        )

    if model.labels.controls != ["constant"] and data is None:
        raise ValueError("To simulate a model with controls, data cannot be None.")

    if data is not None:
        processed_data = process_data(
            df=data,
            has_endogenous_factors=model.endogenous_factors_info.has_endogenous_factors,
            labels=model.labels,
            update_info=model.update_info,
            anchoring_info=model.anchoring,
            purpose="simulation",
        )
        control_data = processed_data["controls"]
        observed_factors = processed_data["observed_factors"]
        data_n_obs = control_data.shape[1]

        if n_obs is not None and data_n_obs != n_obs:
            warnings.warn(
                f"The number of observations inferred from data ({data_n_obs}) and "
                f"n_obs ({n_obs}) are different. n_obs is ignored.",
                stacklevel=2,
            )
        n_obs = data_n_obs

    else:
        control_data = jnp.ones((n_obs, 1))
        n_periods = model.dimensions.n_periods
        observed_factors = jnp.zeros((n_periods, n_obs, 0))

    params_index = get_params_index(
        update_info=model.update_info,
        labels=model.labels,
        dimensions=model.dimensions,
        transition_info=model.transition_info,
        endogenous_factors_info=model.endogenous_factors_info,
    )

    params = params.reindex(params_index)

    parsing_info = create_parsing_info(
        params_index=params.index,  # ty: ignore[invalid-argument-type]
        update_info=model.update_info,
        labels=model.labels,
        anchoring=model.anchoring,
        has_endogenous_factors=model.endogenous_factors_info.has_endogenous_factors,
    )

    if n_obs is None:
        raise ValueError("n_obs must be set by either data or argument")
    states, covs, log_weights, pardict = parse_params(
        params=jnp.array(params["value"].to_numpy()),
        parsing_info=parsing_info,
        dimensions=model.dimensions,
        labels=model.labels,
        n_obs=n_obs,
    )

    aug_measurements, aug_latent_data = _simulate_dataset(
        latent_states=states,
        covs=covs,
        log_weights=log_weights,
        pardict=pardict,
        labels=model.labels,
        dimensions=model.dimensions,
        n_obs=n_obs,
        has_endogenous_factors=model.endogenous_factors_info.has_endogenous_factors,
        update_info=model.update_info,
        control_data=control_data,
        observed_factors=observed_factors,
        policies=policies,  # ty: ignore[invalid-argument-type]
        transition_info=model.transition_info,
    )

    # Create collapsed versions with user-facing periods
    latent_data = _collapse_aug_periods_to_periods(
        df=aug_latent_data,
        factors=model.labels.latent_factors,
        aug_periods_to_periods=model.labels.aug_periods_to_periods,
        endogenous_factors_info=model.endogenous_factors_info,
    )

    # Anchor the collapsed version (anchoring only works with period, not aug_period)
    anchored_latent_data = anchor_states_df(
        states_df=latent_data,
        model_dict=model_dict,
        params=params,
        use_aug_period=False,
    )

    return {
        "unanchored_states": {
            "states": latent_data,
            "state_ranges": create_state_ranges(
                latent_data,
                model.labels.latent_factors,
            ),
        },
        "anchored_states": {
            "states": anchored_latent_data,
            "state_ranges": create_state_ranges(
                anchored_latent_data,
                model.labels.latent_factors,
            ),
        },
        "aug_unanchored_states": {
            "states": aug_latent_data,
            "state_ranges": create_state_ranges(
                aug_latent_data,
                model.labels.latent_factors,
            ),
        },
        "aug_measurements": aug_measurements,
    }


def _simulate_dataset(
    latent_states: Array,
    covs: Array,
    log_weights: Array,
    pardict: dict,
    labels: Labels,
    dimensions: Dimensions,
    n_obs: int,
    *,
    has_endogenous_factors: bool,
    update_info: pd.DataFrame,
    control_data: Array,
    observed_factors: Array,
    policies: list[dict],
    transition_info: TransitionInfo,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Simulate datasets generated by a latent factor model.

    Args:
        latent_states: Array of shape (n_obs, n_mixtures, n_states) with initial
            state estimates.
        covs: Array of shape (n_obs, n_mixtures, n_states, n_states) with initial
            covariance matrices.
        log_weights: Array of shape (n_obs, n_mixtures) with log mixture weights.
        pardict: Dictionary with parsed parameters.
        labels: Labels for the model quantities like factors, periods, controls.
        dimensions: Dimensional information like n_states, n_periods, n_controls.
        n_obs: Number of observations.
        has_endogenous_factors: Whether the model includes endogenous factors.
        update_info: DataFrame with information on measurements for each period.
        control_data: Array of shape (n_periods, n_obs, n_controls) with controls.
        observed_factors: Array of shape (n_periods, n_obs, n_observed_factors).
        policies: List of policy dictionaries specifying stochastic shocks.
        transition_info: Information about transition functions.

    Returns:
        observed_data: DataFrame with simulated measurements.
        latent_data: DataFrame with simulated latent factors.

    """
    policies = policies if policies is not None else []

    n_states = dimensions.n_latent_factors
    if has_endogenous_factors:
        n_aug_periods = dimensions.n_aug_periods - 1
    else:
        n_aug_periods = dimensions.n_aug_periods

    weights = np.exp(log_weights)[0]
    loadings_df = pd.DataFrame(
        data=pardict["loadings"],
        index=update_info.index,
        columns=labels.latent_factors,
    )

    control_params_df = pd.DataFrame(
        data=pardict["controls"],
        index=update_info.index,
        columns=labels.controls,
    )
    meas_sds = pd.DataFrame(
        data=pardict["meas_sds"].reshape(-1, 1),
        index=update_info.index,
    )

    transition_params = pardict["transition"]
    shock_sds = pardict["shock_sds"]

    dist_args = []
    for mixture in range(dimensions.n_mixtures):
        args = {
            "mean": latent_states[0][mixture],
            "cov": covs[0][mixture].T @ covs[0][mixture],
        }
        dist_args.append(args)

    latent_states = np.zeros((n_aug_periods, n_obs, n_states))  # ty: ignore[invalid-assignment]
    latent_states[0] = generate_start_states(n_obs, dimensions, dist_args, weights)

    for t in range(n_aug_periods - 1):
        # if there is a shock in period t, add it here
        policies_t = [p for p in policies if p["aug_period"] == t]
        for policy in policies_t:
            position = labels.latent_factors.index(policy["factor"])
            latent_states[t, :, position] += _get_shock(
                mean=policy["effect_size"],
                sd=policy["standard_deviation"],
                size=n_obs,
            )

        # get combined states and observed factors as jax array
        to_concat = [latent_states[t], observed_factors[t]]
        states = jnp.array(np.concatenate(to_concat, axis=-1))
        # reshaping is just needed for transform sigma points
        states = states.reshape(1, 1, *states.shape)

        # extract trans coeffs for the period
        trans_coeffs = {k: arr[t] for k, arr in transition_params.items()}

        # get anchoring_scaling_factors for the period
        anchoring_scaling_factors = pardict["anchoring_scaling_factors"][
            jnp.array([t, t + 1])
        ]
        # get anchoring constants for the period
        anchoring_constants = pardict["anchoring_constants"][jnp.array([t, t + 1])]

        # call transform_sigma_points and convert result to numpy
        next_states = np.array(
            transform_sigma_points(
                sigma_points=states,
                transition_func=transition_info.func,
                trans_coeffs=trans_coeffs,
                anchoring_scaling_factors=anchoring_scaling_factors,
                anchoring_constants=anchoring_constants,
            ),
        ).reshape(n_obs, -1)

        errors = multivariate_normal(
            mean=np.zeros(n_states),
            cov=np.diag(shock_sds[t] ** 2),
            size=n_obs,
        )
        next_states = next_states + errors

        latent_states[t + 1] = next_states

    observed_data_by_period = []

    for t in range(n_aug_periods):
        meas = pd.DataFrame(
            data=measurements_from_states(
                latent_states[t],  # ty: ignore[invalid-argument-type]
                control_data[t],  # ty: ignore[invalid-argument-type]
                loadings_df.loc[t].to_numpy(),
                control_params_df.loc[t].to_numpy(),
                meas_sds.loc[t].to_numpy().flatten(),
            ),
            columns=loadings_df.loc[t].index,
        )
        meas["aug_period"] = t
        observed_data_by_period.append(meas)

    observed_data = pd.concat(observed_data_by_period, axis=0, sort=True)
    observed_data["id"] = observed_data.index
    observed_data = observed_data.sort_values(["id", "aug_period"])

    latent_data_by_period = []
    for t in range(n_aug_periods):
        lat = pd.DataFrame(data=latent_states[t], columns=labels.latent_factors)
        lat["aug_period"] = t
        latent_data_by_period.append(lat)

    latent_data = pd.concat(latent_data_by_period, axis=0, sort=True)
    latent_data["id"] = latent_data.index
    latent_data = latent_data.sort_values(["id", "aug_period"])
    return observed_data, latent_data


def _collapse_aug_periods_to_periods(
    df: pd.DataFrame,
    factors: tuple[str, ...],
    aug_periods_to_periods: Mapping[int, int],
    endogenous_factors_info: EndogenousFactorsInfo,
) -> pd.DataFrame:
    """Collapse dataframe with aug_period index to user-facing period index.

    For each factor, extracts from the appropriate aug_period based on is_endogenous.

    Args:
        df: DataFrame with columns "aug_period" and "id"
        factors: Tuple of latent factors
        aug_periods_to_periods: Mapping from aug_period to period
        endogenous_factors_info: Information about which factors are endogenous

    Returns:
        pd.DataFrame: DataFrame with "period" column instead of "aug_period"
    """
    df = df.copy()
    if not endogenous_factors_info.has_endogenous_factors:
        return df.rename(columns={"aug_period": "period"})

    df["period"] = df["aug_period"].map(aug_periods_to_periods)
    df["_aug_period_meas_type"] = df["aug_period"].map(
        endogenous_factors_info.aug_periods_to_aug_period_meas_types
    )

    endogenous_cols = [
        fac
        for fac in factors
        if endogenous_factors_info.factor_info[fac].is_endogenous  # ty: ignore[invalid-argument-type]
    ]
    state_cols = [fac for fac in factors if fac not in endogenous_cols]

    out = df.query('_aug_period_meas_type == "endogenous_factors"')[
        ["id", "period", *endogenous_cols]
    ]
    return pd.merge(
        out,
        df.query('_aug_period_meas_type == "states"')[["id", "period", *state_cols]],
        on=["id", "period"],
        how="outer",
    )


def _get_shock(
    mean: float,
    sd: float,
    size: int,
) -> NDArray[np.floating]:
    """Add stochastic effect to a  factor of length n_obs.

    Args:
        mean: mean of the stochastic effect
        sd: standard deviation of the effect
        size: length of resulting array

    Returns:
        shock: 1d array of length n_obs with the stochastic shock

    """
    if sd == 0:
        shock = np.full(size, mean)
    elif sd > 0:
        shock = np.random.normal(mean, sd, size)
    else:
        raise ValueError("No negative standard deviation allowed.")
    return shock


def generate_start_states(
    n_obs: int,
    dimensions: Dimensions,
    dist_args: list[dict],
    weights: NDArray[np.floating],
) -> NDArray[np.floating]:
    """Draw initial states and control variables from a (mixture of) normals.

    Args:
        n_obs: number of observations
        dimensions: Dimensional information like n_states, n_periods, n_controls,
            n_mixtures. See :ref:`dimensions`.
        dist_args: list of dicts of length nmixtures of dictionaries with the
            entries "mean" and "cov" for each mixture distribution.
        weights: Array of mixture weights.

    Returns:
        start_states: shape (n_obs, n_states),
        controls: shape (n_obs, n_controls),

    """
    n_states = dimensions.n_latent_factors
    if np.size(weights) == 1:
        out = multivariate_normal(size=n_obs, **dist_args[0])
    else:
        helper_array = choice(np.arange(len(weights)), p=weights, size=n_obs)
        out = np.zeros((n_obs, n_states))
        for i in range(n_obs):
            out[i] = multivariate_normal(**dist_args[helper_array[i]])

    return out


def measurements_from_states(
    states: NDArray[np.floating],
    controls: NDArray[np.floating],
    loadings: NDArray[np.floating],
    control_params: NDArray[np.floating],
    sds: NDArray[np.floating],
) -> NDArray[np.floating]:
    """Generate the variables that would be observed in practice.

    This generates the data for only one period. Let n_meas be the number
    of measurements in that period.

    Args:
        states: DataFrame of shape (n_obs, n_states)
        controls: DataFrame of shape
            (n_obs, n_controls)
        loadings: numpy array of size (n_meas, n_states)
        control_params: numpy array of size (n_meas, n_controls)
        sds: numpy array of size (n_meas) with the standard deviations
            of the measurements. Measurement error is assumed to be independent
            across measurements.

    Returns:
        measurements: array of shape (n_obs, n_meas) with measurements.

    """
    n_meas = loadings.shape[0]
    n_obs = len(states)
    epsilon = multivariate_normal([0] * n_meas, np.diag(sds**2), n_obs)
    states_part = np.dot(states, loadings.T)
    control_part = np.dot(controls, control_params.T)
    return states_part + control_part + epsilon
