name: skillmodels_rtd
channels:
  - conda-forge
  - janosg
dependencies:
  - python=3.7
  - skillmodels
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3
  - sphinx
  - nbsphinx
  - statsmodels
