{% set data = load_setup_py_data() %}

package:
  name: skillmodels
  version: {{ data.get('version') }}

source:
  git_url: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools
  host:
    python >=3.6
  run:
    - python >=3.6
    - numpy
    - pandas <=1.0.5
    - seaborn
    - scipy
    - jax >=0.1.7
    - jaxlib >=0.1.51

test:
  commands:
    - py.test
  files:
    - skillmodels/tests/
  requires:
    - pytest
    - filterpy


about:
  home: https://github.com/janosg/skillmodels
  license: BSD
  license_file: LICENSE
  summary: Estimate non-linear skill formation models.
