name: skillmodels

channels:
  - defaults
  - conda-forge
  - janosg

dependencies:
  - numpy
  - pandas
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - python=3.5
  - scipy
  - numba
  - statsmodels
  - estimagic=0.0.6

